<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="4" errors="1">
	<testsuite name="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" tests="1" failures="0" errors="1" id="0" hostname="hostname" time="21.630" timestamp="2022-01-01T00:00:00Z">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
		<testcase name="Failure" classname="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" time="0.000">
			<error message="Runtime error"><![CDATA[running tests for  vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation
E1101 10:02:58.832465   21079 tablet.go:242] unable to connect to tablet cell:"test_union" uid:5559: node doesn't exist: /test_union/tablets/test_union-0000005559/Tablet
F1101 10:02:58.842306   21079 run.go:50] listen tcp :16022: bind: address already in use
E1101 10:02:59.023686   17409 cluster_process.go:334] error starting vttablet for tablet uid 5559, grpc port 16023: process 'vttablet' timed out after 10s (err: process 'vttablet' exited prematurely (err: exit status 1))]]></error>
		</testcase>
	</testsuite>
	<testsuite name="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" tests="3" failures="0" errors="0" id="1" hostname="hostname" time="32.140" timestamp="2022-01-01T00:00:00Z">
		<properties>
			<property name="go.version" value="1.0"></property>
		</properties>
		<testcase name="TestAggregateTypes" classname="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" time="0.130"></testcase>
		<testcase name="TestGroupBy" classname="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" time="0.050"></testcase>
		<testcase name="TestDistinct" classname="vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation" time="0.070"></testcase>
		<system-out><![CDATA[running tests for  vitess.io/vitess/go/test/endtoend/vtgate/queries/aggregation]]></system-out>
	</testsuite>
</testsuites>
